### ISSUE TITLE
The Font Packager instantly crashes when opening up a font_package.bin file

### ISSUE THREAD

**Issue by Jasper250** [Lord-Zedd/FontPackager#1]
Debugging with Visual Studio says this:
http://i.imgur.com/dEZSQCx.png

**Comment by NoShotz** [comment]
Happens to me as well

**Comment by twist84** [comment]
So I guess this is an everyone problem and not just a me problem

**Comment by Lord-Zedd** [comment]
That's what I get for switching over to char from uint16 and not actually testing anything, my bad

**Comment by jackrabbit72380** [comment]
Was this issue fixed?

**Comment by Lord-Zedd** [comment]
was an initial upload error and has since been fixed (this issue is closed). if the current release is crashing make a new issue and I'll check it out.

**Comment by jackrabbit72380** [comment]
I figured out how to use it and I had no problum. Thanks for making it! Really helpful!
