### ISSUE TITLE
Charcters are distorted when replaced. 

### ISSUE THREAD

**Issue by demonsako** [Lord-Zedd/FontPackager#3]
When replacing characters they become distorted. Happens even if the new image is the correct size. This can be tested by exporting a character and replacing it with that exact same image. 

![Example](https://user-images.githubusercontent.com/45436850/80993168-77831180-8def-11ea-89ec-76be2e923cf4.png)

![Example_](https://user-images.githubusercontent.com/45436850/80993175-7b169880-8def-11ea-8e77-ad7167df2b93.png)

**Comment by Lord-Zedd** [comment]
well that sucks, guess the cleaned up encoding in 2.0 wasnt as good. I'll look into it

**Comment by Lord-Zedd** [comment]
If you are able to compile, can you confirm this recent commit helped?

**Comment by demonsako** [comment]
> 
> 
> If you are able to compile, can you confirm this recent commit helped?

Unfortunately I don't know how to compile.
