### ISSUE TITLE
Halo 2 Font Upscale

### ISSUE THREAD

**Issue by sakonull** [Lord-Zedd/FontPackager#5]
Not really an issue. Just looking for information. When replacing images with higher resolution ones; in game they're scaled back to original size making them blurry. Is there a way to add three to four times the resolution while scaling properly? 

Unrelated but if you know anything about Halo 2s font breaking after a certain height in resolution that'd be useful too. The end goal is for a high resolution HUD for 2k and 4k monitors.

**Comment by Lord-Zedd** [comment]
It might just be the way they set up fonts for vista (and therefore mcc). Not sure if theres any way around it without trying to reverse things.
As far as limits, what I could find is already implemented as warnings. So if the tool doesn't complain then it should be safe for the game.

**Comment by sakonull** [comment]
I see thanks for the info
